matrix:
  include:
    - os: osx
      language: objective-c # this is a lie
      xcode_project: CommandLine.xcodeproj
      xcode_scheme: CommandLine
      script: xcodebuild -scheme CommandLine test
      osx_image: xcode7.2
    - os: linux
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get install -y libicu-dev
        - ./install-linux-swift.sh
        - export PATH="/swift/usr/bin:${PATH}"
      script:
        - swift build -v
        - .build/debug/CommandLineTests
