shared_variables:
  rightholder: Flinesoft
  project_name: BartyCrouch

rules:
  - xcode_build_phases:
      project_path: <:project_name:>.xcodeproj
      target_name: <:project_name:>Kit
      run_scripts:
        SwiftLint: |
          if [ "${CONFIGURATION}" = "Debug" ]; then
              if which swiftlint > /dev/null; then
                  swiftlint --quiet
              else
                  echo "warning: SwiftLint not installed, download it from https://github.com/realm/SwiftLint"
              fi
          fi

        ProjLint: |
          if [ "${CONFIGURATION}" = "Debug" ]; then
              if which projlint > /dev/null; then
                  projlint lint --xcode --timeout 2 --ignore-network-errors
              else
                  echo "warning: ProjLint not installed, download it from https://github.com/JamitLabs/ProjLint"
              fi
          fi

  - xcode_project_navigator:
      project_path: <:project_name:>.xcodeproj
      sorted:
        - Sources/<:project_name:>
        - Sources/<:project_name:>Kit
        - Sources/SupportingFiles
        - Tests/<:project_name:>KitTests
        - Tests/SupportingFiles
      inner_group_order:
        - assets
        - entitlements
        - plists
        - strings
        - others
        - [code_files, interfaces]
        - folders
      structure:
        - Sources:
            - <:project_name:>
            - <:project_name:>Kit
            - SupportingFiles:
                - Info.plist
        - Tests:
            - <:project_name:>KitTests
            - SupportingFiles:
                - Info.plist
        - RootFiles:
            - beak.swift
            - .projlint.yml
            - .swiftlint.yml
            - Package.swift
        - Products
  - file_content_template:
      matching:
        .swiftlint.yml:
          template_url: "https://raw.githubusercontent.com/JamitLabs/ProjLintTemplates/master/Framework/SwiftLint.stencil"
          parameters:
            rightholder: <:rightholder:>
        .projlint.yml:
          template_url: "https://raw.githubusercontent.com/JamitLabs/ProjLintTemplates/master/Framework/ProjLint.stencil"
          parameters:
            rightholder: <:rightholder:>
            project_name: <:project_name:>
  - file_existence:
      existing_paths:
        - .gitignore
        - .swiftlint.yml
        - CODE_OF_CONDUCT.md
        - CONTRIBUTING.md
        - CHANGELOG.md
        - LICENSE
        - README.md
        - <:project_name:>.podspec
        - Package.swift
        - beak.swift
        - <:project_name:>.xcodeproj/xcshareddata/IDETemplateMacros.plist
        - Sources/SupportingFiles/Info.plist
        - Tests/SupportingFiles/Info.plist
