opt_in_rules:
- empty_count

disabled_rules:
- vertical_whitespace # Turn off until configurable to 2 newlines
- cyclomatic_complexity

included:
- Sources
- Tests

excluded:
- Carthage
- Sources/Constants

line_length: 180
